/**
 * You can specify the following actions in the `Action` element of an IAM policy statement
 * @see https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonmechanicalturk.html
 */
export enum MechanicalturkAction {

  /**
   * Write - The AcceptQualificationRequest operation grants a Worker's request for a Qualification
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_AcceptQualificationRequestOperation.html
   */
  AcceptQualificationRequest = "mechanicalturk:AcceptQualificationRequest",

  /**
   * Write - The ApproveAssignment operation approves the results of a completed assignment
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ApproveAssignmentOperation.html
   */
  ApproveAssignment = "mechanicalturk:ApproveAssignment",

  /**
   * Write - The AssociateQualificationWithWorker operation gives a Worker a Qualification
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_AssociateQualificationWithWorkerOperation.html
   */
  AssociateQualificationWithWorker = "mechanicalturk:AssociateQualificationWithWorker",

  /**
   * Write - The CreateAdditionalAssignmentsForHIT operation increases the maximum number of assignments of an existing HIT
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateAdditionalAssignmentsForHITOperation.html
   */
  CreateAdditionalAssignmentsForHIT = "mechanicalturk:CreateAdditionalAssignmentsForHIT",

  /**
   * Write - The CreateHIT operation creates a new HIT (Human Intelligence Task)
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateHITOperation.html
   */
  CreateHIT = "mechanicalturk:CreateHIT",

  /**
   * Write - The CreateHITType operation creates a new HIT type
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateHITTypeOperation.html
   */
  CreateHITType = "mechanicalturk:CreateHITType",

  /**
   * Write - The CreateHITWithHITType operation creates a new Human Intelligence Task (HIT) using an existing HITTypeID generated by the CreateHITType operation
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateHITWithHITTypeOperation.html
   */
  CreateHITWithHITType = "mechanicalturk:CreateHITWithHITType",

  /**
   * Write - The CreateQualificationType operation creates a new Qualification type, which is represented by a QualificationType data structure
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateQualificationTypeOperation.html
   */
  CreateQualificationType = "mechanicalturk:CreateQualificationType",

  /**
   * Write - The CreateWorkerBlock operation allows you to prevent a Worker from working on your HITs
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateWorkerBlockOperation.html
   */
  CreateWorkerBlock = "mechanicalturk:CreateWorkerBlock",

  /**
   * Write - The DeleteHIT operation disposes of a HIT that is no longer needed
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_DeleteHITOperation.html
   */
  DeleteHIT = "mechanicalturk:DeleteHIT",

  /**
   * Write - The DeleteQualificationType disposes a Qualification type and disposes any HIT types that are associated with the Qualification type
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_DeleteQualificationTypeOperation.html
   */
  DeleteQualificationType = "mechanicalturk:DeleteQualificationType",

  /**
   * Write - The DeleteWorkerBlock operation allows you to reinstate a blocked Worker to work on your HITs
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_DeleteWorkerBlockOperation.html
   */
  DeleteWorkerBlock = "mechanicalturk:DeleteWorkerBlock",

  /**
   * Write - The DisassociateQualificationFromWorker revokes a previously granted Qualification from a user
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_DisassociateQualificationFromWorkerOperation.html
   */
  DisassociateQualificationFromWorker = "mechanicalturk:DisassociateQualificationFromWorker",

  /**
   * Read - The GetAccountBalance operation retrieves the amount of money in your Amazon Mechanical Turk account
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_GetAccountBalanceOperation.html
   */
  GetAccountBalance = "mechanicalturk:GetAccountBalance",

  /**
   * Read - The GetAssignment retrieves an assignment with an AssignmentStatus value of Submitted, Approved, or Rejected, using the assignment's ID
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_GetAssignmentOperation.html
   */
  GetAssignment = "mechanicalturk:GetAssignment",

  /**
   * Read - The GetFileUploadURL operation generates and returns a temporary URL
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_GetFileUploadURLOperation.html
   */
  GetFileUploadURL = "mechanicalturk:GetFileUploadURL",

  /**
   * Read - The GetHIT operation retrieves the details of the specified HIT
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_GetHITOperation.html
   */
  GetHIT = "mechanicalturk:GetHIT",

  /**
   * Read - The GetQualificationScore operation returns the value of a Worker's Qualification for a given Qualification type
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_GetQualificationScoreOperation.html
   */
  GetQualificationScore = "mechanicalturk:GetQualificationScore",

  /**
   * Read - The GetQualificationType operation retrieves information about a Qualification type using its ID
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_GetQualificationTypeOperation.html
   */
  GetQualificationType = "mechanicalturk:GetQualificationType",

  /**
   * List - The ListAssignmentsForHIT operation retrieves completed assignments for a HIT
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListAssignmentsForHITOperation.html
   */
  ListAssignmentsForHIT = "mechanicalturk:ListAssignmentsForHIT",

  /**
   * List - The ListBonusPayments operation retrieves the amounts of bonuses you have paid to Workers for a given HIT or assignment
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListBonusPaymentsOperation.html
   */
  ListBonusPayments = "mechanicalturk:ListBonusPayments",

  /**
   * List - The ListHITs operation returns all of a Requester's HITs
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListHITsOperation.html
   */
  ListHITs = "mechanicalturk:ListHITs",

  /**
   * List - The ListHITsForQualificationType operation returns the HITs that use the given QualififcationType for a QualificationRequirement
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListHITsForQualificationTypeOperation.html
   */
  ListHITsForQualificationType = "mechanicalturk:ListHITsForQualificationType",

  /**
   * List - The ListQualificationRequests operation retrieves requests for Qualifications of a particular Qualification type
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListQualificationRequestsOperation.html
   */
  ListQualificationRequests = "mechanicalturk:ListQualificationRequests",

  /**
   * List - The ListQualificationTypes operation searches for Qualification types using the specified search query, and returns a list of Qualification types
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListQualificationTypesOperation.html
   */
  ListQualificationTypes = "mechanicalturk:ListQualificationTypes",

  /**
   * List - The ListReviewPolicyResultsForHIT operation retrieves the computed results and the actions taken in the course of executing your Review Policies during a CreateHIT operation
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListReviewPolicyResultsForHITOperation.html
   */
  ListReviewPolicyResultsForHIT = "mechanicalturk:ListReviewPolicyResultsForHIT",

  /**
   * List - The ListReviewableHITs operation returns all of a Requester's HITs that have not been approved or rejected
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListReviewableHITsOperation.html
   */
  ListReviewableHITs = "mechanicalturk:ListReviewableHITs",

  /**
   * List - The ListWorkersBlocks operation retrieves a list of Workers who are blocked from working on your HITs
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListWorkerBlocksOperation.html
   */
  ListWorkerBlocks = "mechanicalturk:ListWorkerBlocks",

  /**
   * List - The ListWorkersWithQualificationType operation returns all of the Workers with a given Qualification type
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListWorkersWithQualificationTypeOperation.html
   */
  ListWorkersWithQualificationType = "mechanicalturk:ListWorkersWithQualificationType",

  /**
   * Write - The NotifyWorkers operation sends an email to one or more Workers that you specify with the Worker ID
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_NotifyWorkersOperation.html
   */
  NotifyWorkers = "mechanicalturk:NotifyWorkers",

  /**
   * Write - The RejectAssignment operation rejects the results of a completed assignment
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_RejectAssignmentOperation.html
   */
  RejectAssignment = "mechanicalturk:RejectAssignment",

  /**
   * Write - The RejectQualificationRequest operation rejects a user's request for a Qualification
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_RejectQualificationRequestOperation.html
   */
  RejectQualificationRequest = "mechanicalturk:RejectQualificationRequest",

  /**
   * Write - The SendBonus operation issues a payment of money from your account to a Worker
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_SendBonusOperation.html
   */
  SendBonus = "mechanicalturk:SendBonus",

  /**
   * Write - The SendTestEventNotification operation causes Amazon Mechanical Turk to send a notification message as if a HIT event occurred, according to the provided notification specification
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_SendTestEventNotificationOperation.html
   */
  SendTestEventNotification = "mechanicalturk:SendTestEventNotification",

  /**
   * Write - The UpdateExpirationForHIT operation allows you extend the expiration time of a HIT beyond is current expiration or expire a HIT immediately
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_UpdateExpirationForHITOperation.html
   */
  UpdateExpirationForHIT = "mechanicalturk:UpdateExpirationForHIT",

  /**
   * Write - The UpdateHITReviewStatus operation toggles the status of a HIT
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_UpdateHITReviewStatusOperation.html
   */
  UpdateHITReviewStatus = "mechanicalturk:UpdateHITReviewStatus",

  /**
   * Write - The UpdateHITTypeOfHIT operation allows you to change the HITType properties of a HIT
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_UpdateHITTypeOfHITOperation.html
   */
  UpdateHITTypeOfHIT = "mechanicalturk:UpdateHITTypeOfHIT",

  /**
   * Write - The UpdateNotificationSettings operation creates, updates, disables or re-enables notifications for a HIT type
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_UpdateNotificationSettingsOperation.html
   */
  UpdateNotificationSettings = "mechanicalturk:UpdateNotificationSettings",

  /**
   * Write - The UpdateQualificationType operation modifies the attributes of an existing Qualification type, which is represented by a QualificationType data structure
   * @see https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_UpdateQualificationTypeOperation.html
   */
  UpdateQualificationType = "mechanicalturk:UpdateQualificationType",

  /**
   * * - Grant all mechanicalturk permissions
   * @see https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonmechanicalturk.html
   */
  All = "mechanicalturk:*",
}

/**
 * You can specify the following resources in the `Resource` element of an IAM policy statement
 * @see https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonmechanicalturk.html
 */
export const MechanicalturkResource = {
}

