/**
 * You can specify the following actions in the `Action` element of an IAM policy statement
 * @see https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazontranscribe.html
 */
export enum TranscribeAction {

  /**
   * Write - Grants permission to create an analytics category. Amazon Transcribe applies the conditions specified by your analytics categories to your call analytics jobs
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateCallAnalyticsCategory.html
   */
  CreateCallAnalyticsCategory = "transcribe:CreateCallAnalyticsCategory",

  /**
   * Write - Grants permission to create a new custom language model
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateLanguageModel.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:RequestTag/${TagKey}`: Filters access by requiring tag values present in a resource creation request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `aws:TagKeys`: Filters access by requiring the presence of mandatory tags in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ArrayOfString `ArrayOfString`})
   */
  CreateLanguageModel = "transcribe:CreateLanguageModel",

  /**
   * Write - Grants permission to create a new custom vocabulary that you can use to change the way Amazon Transcribe Medical handles transcription of an audio file
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateMedicalVocabulary.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:RequestTag/${TagKey}`: Filters access by requiring tag values present in a resource creation request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `aws:TagKeys`: Filters access by requiring the presence of mandatory tags in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ArrayOfString `ArrayOfString`})
   */
  CreateMedicalVocabulary = "transcribe:CreateMedicalVocabulary",

  /**
   * Write - Grants permission to create a new custom vocabulary that you can use to change the way Amazon Transcribe handles transcription of an audio file
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateVocabulary.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:RequestTag/${TagKey}`: Filters access by requiring tag values present in a resource creation request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `aws:TagKeys`: Filters access by requiring the presence of mandatory tags in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ArrayOfString `ArrayOfString`})
   */
  CreateVocabulary = "transcribe:CreateVocabulary",

  /**
   * Write - Grants permission to create a new vocabulary filter that you can use to filter out words from the transcription of an audio file generated by Amazon Transcribe
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateVocabularyFilter.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:RequestTag/${TagKey}`: Filters access by requiring tag values present in a resource creation request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `aws:TagKeys`: Filters access by requiring the presence of mandatory tags in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ArrayOfString `ArrayOfString`})
   */
  CreateVocabularyFilter = "transcribe:CreateVocabularyFilter",

  /**
   * Write - Grants permission to delete a call analytics category using its name from Amazon Transcribe
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteCallAnalyticsCategory.html
   */
  DeleteCallAnalyticsCategory = "transcribe:DeleteCallAnalyticsCategory",

  /**
   * Write - Grants permission to delete a previously submitted call analytics job along with any other generated results such as the transcription, models, and so on
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteCallAnalyticsJob.html
   */
  DeleteCallAnalyticsJob = "transcribe:DeleteCallAnalyticsJob",

  /**
   * Write - Grants permission to delete a previously created custom language model
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteLanguageModel.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.languagemodel `TranscribeResource.languagemodel`} 
   */
  DeleteLanguageModel = "transcribe:DeleteLanguageModel",

  /**
   * Write - Grants permission to delete a previously submitted medical transcription job
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteMedicalTranscriptionJob.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.medicaltranscriptionjob `TranscribeResource.medicaltranscriptionjob`} 
   */
  DeleteMedicalTranscriptionJob = "transcribe:DeleteMedicalTranscriptionJob",

  /**
   * Write - Grants permission to delete a medical vocabulary from Amazon Transcribe
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteMedicalVocabulary.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.medicalvocabulary `TranscribeResource.medicalvocabulary`} 
   */
  DeleteMedicalVocabulary = "transcribe:DeleteMedicalVocabulary",

  /**
   * Write - Grants permission to delete a previously submitted transcription job along with any other generated results such as the transcription, models, and so on
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteTranscriptionJob.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.transcriptionjob `TranscribeResource.transcriptionjob`} 
   */
  DeleteTranscriptionJob = "transcribe:DeleteTranscriptionJob",

  /**
   * Write - Grants permission to delete a vocabulary from Amazon Transcribe
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteVocabulary.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.vocabulary `TranscribeResource.vocabulary`} 
   */
  DeleteVocabulary = "transcribe:DeleteVocabulary",

  /**
   * Write - Grants permission to delete a vocabulary filter from Amazon Transcribe
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_DeleteVocabularyFilter.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.vocabularyfilter `TranscribeResource.vocabularyfilter`} 
   */
  DeleteVocabularyFilter = "transcribe:DeleteVocabularyFilter",

  /**
   * Read - Grants permission to return information about a custom language model
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_DescribeLanguageModel.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.languagemodel `TranscribeResource.languagemodel`} 
   */
  DescribeLanguageModel = "transcribe:DescribeLanguageModel",

  /**
   * Read - Grants permission to retrieve information about a call analytics category
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_GetCallAnalyticsCategory.html
   */
  GetCallAnalyticsCategory = "transcribe:GetCallAnalyticsCategory",

  /**
   * Read - Grants permission to return information about a call analytics job
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_GetCallAnalyticsJob.html
   */
  GetCallAnalyticsJob = "transcribe:GetCallAnalyticsJob",

  /**
   * Read - Grants permission to return information about a medical transcription job
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_GetMedicalTranscriptionJob.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.medicaltranscriptionjob `TranscribeResource.medicaltranscriptionjob`} 
   */
  GetMedicalTranscriptionJob = "transcribe:GetMedicalTranscriptionJob",

  /**
   * Read - Grants permission to get information about a medical vocabulary
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_GetMedicalVocabulary.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.medicalvocabulary `TranscribeResource.medicalvocabulary`} 
   */
  GetMedicalVocabulary = "transcribe:GetMedicalVocabulary",

  /**
   * Read - Grants permission to return information about a transcription job
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_GetTranscriptionJob.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.transcriptionjob `TranscribeResource.transcriptionjob`} 
   */
  GetTranscriptionJob = "transcribe:GetTranscriptionJob",

  /**
   * Read - Grants permission to to get information about a vocabulary
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_GetVocabulary.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.vocabulary `TranscribeResource.vocabulary`} 
   */
  GetVocabulary = "transcribe:GetVocabulary",

  /**
   * Read - Grants permission to get information about a vocabulary filter
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_GetVocabularyFilter.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.vocabularyfilter `TranscribeResource.vocabularyfilter`} 
   */
  GetVocabularyFilter = "transcribe:GetVocabularyFilter",

  /**
   * List - Grants permission to list call analytics categories that has been created
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_ListCallAnalyticsCategories.html
   */
  ListCallAnalyticsCategories = "transcribe:ListCallAnalyticsCategories",

  /**
   * List - Grants permission to list call analytics jobs with the specified status
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_ListCallAnalyticsJobs.html
   */
  ListCallAnalyticsJobs = "transcribe:ListCallAnalyticsJobs",

  /**
   * List - Grants permission to list custom language models
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_ListLanguageModels.html
   */
  ListLanguageModels = "transcribe:ListLanguageModels",

  /**
   * List - Grants permission to list medical transcription jobs with the specified status
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_ListMedicalTranscriptionJobs.html
   */
  ListMedicalTranscriptionJobs = "transcribe:ListMedicalTranscriptionJobs",

  /**
   * List - Grants permission to return a list of medical vocabularies that match the specified criteria. If no criteria are specified, returns the entire list of vocabularies
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_ListMedicalVocabularies.html
   */
  ListMedicalVocabularies = "transcribe:ListMedicalVocabularies",

  /**
   * Read - Grants permission to list tags for a resource
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_ListTagsForResource.html
   */
  ListTagsForResource = "transcribe:ListTagsForResource",

  /**
   * List - Grants permission to list transcription jobs with the specified status
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_ListTranscriptionJobs.html
   */
  ListTranscriptionJobs = "transcribe:ListTranscriptionJobs",

  /**
   * List - Grants permission to return a list of vocabularies that match the specified criteria. If no criteria are specified, returns the entire list of vocabularies
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_ListVocabularies.html
   */
  ListVocabularies = "transcribe:ListVocabularies",

  /**
   * List - Grants permission to return a list of vocabulary filters that match the specified criteria. If no criteria are specified, returns the at most 5 vocabulary filters
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_ListVocabularyFilters.html
   */
  ListVocabularyFilters = "transcribe:ListVocabularyFilters",

  /**
   * Write - Grants permission to start an asynchronous analytics job that not only transcribes the audio recording of a caller and agent, but also returns additional insights
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_StartCallAnalyticsJob.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `transcribe:OutputEncryptionKMSKeyId`: Filters access based on the KMS key id included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `transcribe:OutputLocation`: Filters access based on the output location included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   */
  StartCallAnalyticsJob = "transcribe:StartCallAnalyticsJob",

  /**
   * Write - Grants permission to start a protocol where audio is streamed to Transcribe Medical and the transcription results are streamed to your application
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartMedicalStreamTranscription.html
   */
  StartMedicalStreamTranscription = "transcribe:StartMedicalStreamTranscription",

  /**
   * Write - Grants permission to start a WebSocket where audio is streamed to Transcribe Medical and the transcription results are streamed to your application
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartMedicalStreamTranscriptionWebSocket.html
   */
  StartMedicalStreamTranscriptionWebSocket = "transcribe:StartMedicalStreamTranscriptionWebSocket",

  /**
   * Write - Grants permission to start an asynchronous job to transcribe medical speech to text
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_StartMedicalTranscriptionJob.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `transcribe:OutputBucketName`: Filters access based on the output bucket name included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `transcribe:OutputEncryptionKMSKeyId`: Filters access based on the KMS key id included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `transcribe:OutputKey`: Filters access based on the output key included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `aws:RequestTag/${TagKey}`: Filters access by requiring tag values present in a resource creation request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `aws:TagKeys`: Filters access by requiring the presence of mandatory tags in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ArrayOfString `ArrayOfString`})
   */
  StartMedicalTranscriptionJob = "transcribe:StartMedicalTranscriptionJob",

  /**
   * Write - Grants permission to start a bidirectional HTTP2 stream to transcribe speech to text in real time
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartStreamTranscription.html
   */
  StartStreamTranscription = "transcribe:StartStreamTranscription",

  /**
   * Write - Grants permission to start a websocket stream to transcribe speech to text in real time
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartStreamTranscriptionWebSocket.html
   */
  StartStreamTranscriptionWebSocket = "transcribe:StartStreamTranscriptionWebSocket",

  /**
   * Write - Grants permission to start an asynchronous job to transcribe speech to text
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_StartTranscriptionJob.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `transcribe:OutputBucketName`: Filters access based on the output bucket name included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `transcribe:OutputEncryptionKMSKeyId`: Filters access based on the KMS key id included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `transcribe:OutputKey`: Filters access based on the output key included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `aws:RequestTag/${TagKey}`: Filters access by requiring tag values present in a resource creation request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `aws:TagKeys`: Filters access by requiring the presence of mandatory tags in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ArrayOfString `ArrayOfString`})
   */
  StartTranscriptionJob = "transcribe:StartTranscriptionJob",

  /**
   * Tagging - Grants permission to tag a resource with given key value pairs
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_TagResource.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:RequestTag/${TagKey}`: Filters access by requiring tag values present in a resource creation request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `aws:TagKeys`: Filters access by requiring the presence of mandatory tags in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ArrayOfString `ArrayOfString`})
   */
  TagResource = "transcribe:TagResource",

  /**
   * Tagging - Grants permission to untag a resource with given key
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_UntagResource.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:TagKeys`: Filters access by requiring the presence of mandatory tags in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ArrayOfString `ArrayOfString`})
   */
  UntagResource = "transcribe:UntagResource",

  /**
   * Write - Grants permission to update the call analytics category with new values. The UpdateCallAnalyticsCategory operation overwrites all of the existing information with the values that you provide in the request
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_UpdateCallAnalyticsCategory.html
   */
  UpdateCallAnalyticsCategory = "transcribe:UpdateCallAnalyticsCategory",

  /**
   * Write - Grants permission to update an existing medical vocabulary with new values. The UpdateMedicalVocabulary operation overwrites all of the existing information with the values that you provide in the request
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_UpdateMedicalVocabulary.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.medicalvocabulary `TranscribeResource.medicalvocabulary`} 
   */
  UpdateMedicalVocabulary = "transcribe:UpdateMedicalVocabulary",

  /**
   * Write - Grants permission to update an existing vocabulary with new values. The UpdateVocabulary operation overwrites all of the existing information with the values that you provide in the request
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_UpdateVocabulary.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.vocabulary `TranscribeResource.vocabulary`} 
   */
  UpdateVocabulary = "transcribe:UpdateVocabulary",

  /**
   * Write - Grants permission to update an existing vocabulary filter with new values. The UpdateVocabularyFilter operation overwrites all of the existing information with the values that you provide in the request
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_UpdateVocabularyFilter.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.vocabularyfilter `TranscribeResource.vocabularyfilter`} 
   */
  UpdateVocabularyFilter = "transcribe:UpdateVocabularyFilter",

  /**
   * * - Grant all transcribe permissions
   * @see https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazontranscribe.html
   * 
   * @remarks
   * 
   * It can be used with the following resource types in the `Resource` element of IAM policy statements:
   * - {@link TranscribeResource.languagemodel `TranscribeResource.languagemodel`} 
   * - {@link TranscribeResource.medicaltranscriptionjob `TranscribeResource.medicaltranscriptionjob`} 
   * - {@link TranscribeResource.medicalvocabulary `TranscribeResource.medicalvocabulary`} 
   * - {@link TranscribeResource.transcriptionjob `TranscribeResource.transcriptionjob`} 
   * - {@link TranscribeResource.vocabulary `TranscribeResource.vocabulary`} 
   * - {@link TranscribeResource.vocabularyfilter `TranscribeResource.vocabularyfilter`} 
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:RequestTag/${TagKey}`: Filters access by requiring tag values present in a resource creation request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `aws:TagKeys`: Filters access by requiring the presence of mandatory tags in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_ArrayOfString `ArrayOfString`})
   * - `transcribe:OutputEncryptionKMSKeyId`: Filters access based on the KMS key id included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `transcribe:OutputLocation`: Filters access based on the output location included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `transcribe:OutputBucketName`: Filters access based on the output bucket name included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   * - `transcribe:OutputKey`: Filters access based on the output key included in the request ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazontranscribe.html#amazontranscribe-policy-keys documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   */
  All = "transcribe:*",
}

/**
 * You can specify the following resources in the `Resource` element of an IAM policy statement
 * @see https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazontranscribe.html
 */
export const TranscribeResource = {

  /**
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_TranscriptionJob.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:ResourceTag/${TagKey}`: Filters access by requiring tag value associated with the resource ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   */
  transcriptionjob: (options: Partial<{partition: string, region: string, account: string, jobName: string}> = {}) => `arn:${options.partition || '*'}:transcribe:${options.region || '*'}:${options.account || '*'}:transcription-job/${options.jobName || '*'}`,

  /**
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateVocabulary.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:ResourceTag/${TagKey}`: Filters access by requiring tag value associated with the resource ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   */
  vocabulary: (options: Partial<{partition: string, region: string, account: string, vocabularyName: string}> = {}) => `arn:${options.partition || '*'}:transcribe:${options.region || '*'}:${options.account || '*'}:vocabulary/${options.vocabularyName || '*'}`,

  /**
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateVocabularyFilter.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:ResourceTag/${TagKey}`: Filters access by requiring tag value associated with the resource ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   */
  vocabularyfilter: (options: Partial<{partition: string, region: string, account: string, vocabularyFilterName: string}> = {}) => `arn:${options.partition || '*'}:transcribe:${options.region || '*'}:${options.account || '*'}:vocabulary-filter/${options.vocabularyFilterName || '*'}`,

  /**
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_LanguageModel.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:ResourceTag/${TagKey}`: Filters access by requiring tag value associated with the resource ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   */
  languagemodel: (options: Partial<{partition: string, region: string, account: string, modelName: string}> = {}) => `arn:${options.partition || '*'}:transcribe:${options.region || '*'}:${options.account || '*'}:language-model/${options.modelName || '*'}`,

  /**
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_MedicalTranscriptionJob.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:ResourceTag/${TagKey}`: Filters access by requiring tag value associated with the resource ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   */
  medicaltranscriptionjob: (options: Partial<{partition: string, region: string, account: string, jobName: string}> = {}) => `arn:${options.partition || '*'}:transcribe:${options.region || '*'}:${options.account || '*'}:medical-transcription-job/${options.jobName || '*'}`,

  /**
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateMedicalVocabulary.html
   * 
   * @remarks
   * 
   * It can be used with the following condition keys in the `Condition` element of an IAM policy statements:
   * - `aws:ResourceTag/${TagKey}`: Filters access by requiring tag value associated with the resource ({@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-globally-available documentation}, type: {@link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String `String`})
   */
  medicalvocabulary: (options: Partial<{partition: string, region: string, account: string, vocabularyName: string}> = {}) => `arn:${options.partition || '*'}:transcribe:${options.region || '*'}:${options.account || '*'}:medical-vocabulary/${options.vocabularyName || '*'}`,

  /**
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_CallAnalyticsJob.html
   */
  callanalyticsjob: (options: Partial<{partition: string, region: string, account: string, jobName: string}> = {}) => `arn:${options.partition || '*'}:transcribe:${options.region || '*'}:${options.account || '*'}:analytics-job/${options.jobName || '*'}`,

  /**
   * @see https://docs.aws.amazon.com/transcribe/latest/dg/API_CreateCallAnalyticsCategory.html
   */
  callanalyticscategory: (options: Partial<{partition: string, region: string, account: string, categoryName: string}> = {}) => `arn:${options.partition || '*'}:transcribe:${options.region || '*'}:${options.account || '*'}:analytics-category/${options.categoryName || '*'}`,
}

